# for details: https://jek4wik.github.io/Main
title: Kinkie's wiki lab
description:  > # this means to ignore newlines
    Assorted notetaking, testing using jeckyll as a wiki site as well
baseurl: "" # the subpath of your site, e.g. /blog
url: "htpps://kinkie.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-toc
  - jekyll-archives
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-last-modified-at
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-paginate-v2
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-watch

encoding: UTF-8
lang: en # fr is also supported ; feel free to contribute other languages
date_format: "%-d %b %Y"

exclude:
  - Gemfile
  - Gemfile.lock
  - img/brand
  - vendor # For CI cache

collections:
  wiki:
    output: true
    permalink: "/:path" 
    path: "" # avoid wiki in the url
#  wiki-legacy:
#    output: true
#    permalink: "/:path"
#    path: ""
  special:
    output: true
    permalink: "/:path"
    path: ""
  global:
    output: true
    permalink: "/:path"
    path: ""
